openapi: 3.2.0
info:
  title: SignalWire REST Conference Tokens API
  version: 1.0.0
  contact:
    name: SignalWire
    url: https://support.signalwire.com/portal/en/newticket?departmentId=1029313000000006907&layoutId=1029313000000074011
    email: support@signalwire.com
  license:
    name: MIT
    url: https://github.com/signalwire/docs/blob/main/LICENSE
  termsOfService: https://signalwire.com/legal/signalwire-cloud-agreement
  description: Manage conference tokens
servers:
- url: https://{space_name}.signalwire.com
  description: SignalWire API
  variables:
    space_name:
      default: '{Your_Space_Name}'
      description: Your SignalWire Space name
security:
- SignalWireBasicAuth: []
tags:
- name: Conference Tokens
  description: Manage conference tokens
  externalDocs:
    url: https://signalwire.com/docs/apis
    description: Developer documentation on SignalWire REST APIs
paths:
  /api/video/conference_tokens/{id}:
    get:
      operationId: get_conference_token
      summary: Get conference token
      description: 'Find a conference token by ID.


        #### Permissions


        The API token used to authenticate must have the following scope(s) enabled to make a successful request: _Video_.


        [Learn more about API scopes](/docs/platform/your-signalwire-api-space).'
      parameters:
      - $ref: '#/components/parameters/Video.ConferenceTokenPathID'
      responses:
        '200':
          description: Conference token response object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video.ConferenceToken'
        '400':
          description: The request is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode400'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode401'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode404'
        '500':
          description: An internal server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode500'
      tags:
      - Conference Tokens
  /api/video/conference_tokens/{id}/reset:
    post:
      operationId: reset_conference_token
      summary: Reset conference token
      description: 'Reset a conference token by ID.


        #### Permissions


        The API token used to authenticate must have the following scope(s) enabled to make a successful request: _Video_.


        [Learn more about API scopes](/docs/platform/your-signalwire-api-space).'
      parameters:
      - $ref: '#/components/parameters/Video.ConferenceTokenPathID'
      responses:
        '200':
          description: Conference token response object.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video.ConferenceToken'
        '400':
          description: The request is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode400'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode401'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode404'
        '500':
          description: An internal server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode500'
      tags:
      - Conference Tokens
  /api/video/conferences/{id}/conference_tokens:
    get:
      operationId: list_conference_tokens
      summary: List conference tokens
      description: 'List conference tokens.


        #### Permissions


        The API token used to authenticate must have the following scope(s) enabled to make a successful request: _Video_.


        [Learn more about API scopes](/docs/platform/your-signalwire-api-space).'
      parameters:
      - $ref: '#/components/parameters/Video.ConferencePathID'
      - $ref: '#/components/parameters/Video.ListConferenceTokensRequest.page_number'
      - $ref: '#/components/parameters/Video.ListConferenceTokensRequest.page_size'
      - $ref: '#/components/parameters/Video.ListConferenceTokensRequest.page_token'
      responses:
        '200':
          description: The request has succeeded.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video.ListConferenceTokensResponse'
        '400':
          description: The request is invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode400'
        '401':
          description: Access is unauthorized.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode401'
        '404':
          description: The server cannot find the requested resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode404'
        '422':
          description: The request contains invalid parameters. See errors for details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Video.VideoStatusCode422'
        '500':
          description: An internal server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Types.StatusCodes.StatusCode500'
      tags:
      - Conference Tokens
components:
  parameters:
    Video.ListConferenceTokensRequest.page_number:
      name: page_number
      in: query
      required: false
      description: Page number to return. Requires `page_token` for values greater than 0.
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
      explode: false
    Video.ListConferenceTokensRequest.page_size:
      name: page_size
      in: query
      required: false
      description: Specify the number of results to return on a single page. The default page size is `50` and the maximum is `1000`.
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        default: 50
      explode: false
    Video.ConferenceTokenPathID:
      name: id
      in: path
      required: true
      description: Unique ID of the conference token.
      schema:
        $ref: '#/components/schemas/uuid'
    Video.ListConferenceTokensRequest.page_token:
      name: page_token
      in: query
      required: false
      description: Token for cursor-based pagination. Required when `page_number` is greater than 0.
      schema:
        type: string
      explode: false
    Video.ConferencePathID:
      name: id
      in: path
      required: true
      description: Unique ID of the video conference.
      schema:
        $ref: '#/components/schemas/uuid'
  schemas:
    Types.StatusCodes.StatusCode401:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          enum:
          - Unauthorized
      unevaluatedProperties:
        not: {}
      description: Access is unauthorized.
    uuid:
      type: string
      format: uuid
      description: Universal Unique Identifier.
    Video.PaginationLinks:
      type: object
      required:
      - self
      - first
      properties:
        self:
          type: string
          description: Link to the current page.
          examples:
          - https://example.signalwire.com/api/video/rooms?page=2
        first:
          type: string
          description: Link to the first page.
          examples:
          - https://example.signalwire.com/api/video/rooms?page=1
        next:
          type: string
          description: Link to the next page.
          examples:
          - https://example.signalwire.com/api/video/rooms?page=3
        prev:
          type: string
          description: Link to the previous page.
          examples:
          - https://example.signalwire.com/api/video/rooms?page=1
      unevaluatedProperties:
        not: {}
      description: Pagination links for list responses.
    Video.ListConferenceTokensResponse:
      type: object
      required:
      - links
      - data
      properties:
        links:
          allOf:
          - $ref: '#/components/schemas/Video.PaginationLinks'
          description: Pagination links.
        data:
          type: array
          items:
            $ref: '#/components/schemas/Video.ConferenceToken'
          description: List of conference tokens.
      unevaluatedProperties:
        not: {}
      description: List conference tokens response.
    Types.StatusCodes.StatusCode404:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          enum:
          - Not Found
      unevaluatedProperties:
        not: {}
      description: The server cannot find the requested resource.
    Video.ConferenceToken:
      type: object
      required:
      - id
      - name
      - token
      - scopes
      properties:
        id:
          allOf:
          - $ref: '#/components/schemas/uuid'
          description: Unique identifier for the conference token.
          examples:
          - c22d24f6-5a47-4597-9a23-c7d01e696b92
        name:
          anyOf:
          - type: string
          - type: 'null'
          description: Name of the conference token.
          examples:
          - My First Token
        token:
          type: string
          description: Conference token's randomly generated sequence.
          examples:
          - vpt_62c65414de4d067d07415a7ced8183be
        scopes:
          type: array
          items:
            type: string
          description: List of permissions.
          examples:
          - - room.member.audio_mute
      unevaluatedProperties:
        not: {}
      description: A conference token object.
    Types.StatusCodes.StatusCode500:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          enum:
          - Internal Server Error
      unevaluatedProperties:
        not: {}
      description: An internal server error occurred.
    Types.StatusCodes.RestApiErrorItem:
      type: object
      required:
      - type
      - code
      - message
      - url
      properties:
        type:
          type: string
          description: The category of error.
          examples:
          - validation_error
        code:
          type: string
          description: A specific error code.
          examples:
          - invalid_parameter
        message:
          type: string
          description: A description of what caused the error.
          examples:
          - Name must be present
        attribute:
          anyOf:
          - type: string
          - type: 'null'
          description: The request parameter that caused the error, if applicable.
          examples:
          - name
        url:
          type: string
          description: A link to documentation about this error.
          examples:
          - https://signalwire.com/docs/apis/error-codes
      unevaluatedProperties:
        not: {}
      description: Details about a specific error.
    Types.StatusCodes.StatusCode400:
      type: object
      required:
      - error
      properties:
        error:
          type: string
          enum:
          - Bad Request
      unevaluatedProperties:
        not: {}
      description: The request is invalid.
    Video.VideoStatusCode422:
      type: object
      required:
      - errors
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Types.StatusCodes.RestApiErrorItem'
          description: List of validation errors.
      unevaluatedProperties:
        not: {}
      description: The request contains invalid parameters. See errors for details.
      examples:
      - statusCode: 422
        errors:
        - type: validation_error
          code: invalid_parameter
          message: Name must be present
          attribute: name
          url: https://signalwire.com/docs/apis/error-codes
  securitySchemes:
    SignalWireBasicAuth:
      type: http
      scheme: Basic
      description: 'SignalWire Basic Authentication using Project ID and API Token.


        The client sends HTTP requests with the Authorization header containing

        the word Basic followed by a space and a base64-encoded string of project_id:token.

        The project ID will be used as the username and the API token as the password.


        Example:

        ```

        Authorization: Basic base64(project_id:token)

        ```'
      x-fern-basic:
        username:
          name: project_id
          env: SIGNALWIRE_PROJECT_ID
        password:
          name: api_token
          env: SIGNALWIRE_API_TOKEN
    SignalWireBearerAuth:
      type: http
      scheme: Bearer
      description: 'SignalWire Bearer Token Authentication for subscriber endpoints.

        The client sends HTTP requests with the Authorization header containing

        the word Bearer followed by a space and the subscriber token.


        Example:

        ```

        Authorization: Bearer <subscriber_token>

        ```'
